# Generated by Django 3.2.6 on 2021-08-27 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hero',
            old_name='alias',
            new_name='description',
        ),
    ]
