# Generated by Django 3.2.6 on 2021-08-27 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_rename_alias_hero_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hero',
            new_name='Divar',
        ),
    ]
